---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Pacific/Noumea"
    assignees:
      - "tamere-allo-peter"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "all"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
