---

name: Checks

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: install linters
        run: python -m pip install yamllint pylint flake8 flake8-import-order

      - name: lint YAML files, excluding examples
        run: yamllint --strict $(git ls-files '*.yaml' '*.yml' '.yamllint' | grep -v ^examples/)

      - name: lint Python code through flake8
        run: flake8 .

      - name: lint Python code through pylint
        run: pylint yamlfixer

  tests:
    name: Tests
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Append GitHub Actions system path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: install coveralls
        run: pip install coveralls

      - name: install yamlfixer
        run: pip install .

      - name: launch tests
        run: coverage run --source=yamlfixer -m unittest discover

  automerge:
    name: AutoMerge
    needs: [lint, tests]
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #  uses: actions/checkout@v2

      - name: Create Pull Request
        id: createpr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""  # If blank, default: triggered branch
          destination_branch: "main"  # If blank, default: master
          github_token: ${{secrets.GITHUB_TOKEN}}

      # Activate auto merge
      - if: steps.createpr.outputs.pr_number != 0
        name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          pull-request-number: ${{steps.createpr.outputs.pr_number}}
          merge-method: merge  # merge, squash, rebase
          token: ${{secrets.GITHUB_TOKEN}}  # Works despite what the documentation says
