---
name: Publish a new release on GitHub

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: '*.*.*'
  pull_request:
    branches: [main]
    tags: '*.*.*'

jobs:
  new-gh-release:
    name: Publish a new GitHub release
    if: startsWith(github.ref, 'refs/tags')  # Do this only if commit is tagged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generate Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
