---
name: Publish a new release on GitHub

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: '*.*.*'
  pull_request:
    branches: [main]
    tags: '*.*.*'

jobs:
  new-gh-release:
    name: Publish a new GitHub release
    if: startsWith(github.ref, 'refs/tags')  # Do this only if commit is tagged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: false
          generateReleaseNotes: true
